#ifndef CLOUDCONNECT_GLOBAL_H
#define CLOUDCONNECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLOUDCONNECT_LIBRARY)
#  define CLOUDCONNECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLOUDCONNECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLOUDCONNECT_GLOBAL_H
